### ISSUE TITLE
CR : Display of the cash amount available

### ISSUE THREAD

**Issue by zinse22** [kienct89/vmcs#1]
Hi Dattu,

@dattu1729 , Please find the attached change request detail. This needs to be delivered as part of Release 1.0.9. For more information please refer to Change Request document.

**Comment by dattu1729** [comment]
Hi Kin,

@kienct89 Updated design document with below changes.

-Added Sequence diagrams for Update Coin Display, CoinLabelItem, CoinLabelItemDisplay
-Added "GetTotalCoin" operation for Store Controller class
-Remove association of CoinDisplay to ButtonItemDisplay
-Add association of CoinDisplay to CoinLabelItemDisplay

Added "DisplayTotalCoin", "SetActiveTotalCoin" operations for Maintenance Panel class. For complete details please verify the design document. Please Do the coding changes for this enhancement.

**Comment by kienct89** [comment]
Hi Dattu, 
I've completed the enhancement and committed to cr-branch in the following commit (https://github.com/kienct89/vmcs/commit/6d6bcc7f1b186860e53567b6df3f7ebb34d2592e)

Screenshot in my local testing:

![image](https://cloud.githubusercontent.com/assets/3182992/10116929/3c732e14-6477-11e5-80d4-265fc3b2a3a1.png)

Please do a code review.

**Comment by dattu1729** [comment]
@kienct89 , Code review done and no comments. We can release it for Testing.

Hi Victor,
This CR changes and done. Please do testing.

**Comment by victordc** [comment]
Dear Dattu,

The testing is done and ready to be released

![image](https://cloud.githubusercontent.com/assets/5611431/10116939/bbd4788e-6477-11e5-9259-5a4434846bbc.png)

**Comment by caesarloh** [comment]
Verified. Working as expected.

**Comment by yj88** [comment]
Approved for release under 1.0.9. CR merged back to trunk.

**Comment by zinse22** [comment]
Released and closed.
