### ISSUE TITLE
Defect: To fix not clear the values of amount displayed

### ISSUE THREAD

**Issue by zinse22** [kienct89/vmcs#2]
Hi Dattu,

A defect to fix not clear the values of amount displayed on the completion of a Maintenance session. Please see attach details for Defect Change Request.
This need to be part of VCMS Release 1.0.9.

**Comment by dattu1729** [comment]
Hi Nick, 

Can you please check this defect. Need to clear the amount displayed value. For more information please check defect details. If need to any help let me know.

**Comment by nicklam345** [comment]
Hi Dattu, 
Bug was fixed in this commit. (https://github.com/kienct89/vmcs/commit/7f774f0ea8c932cb356e26527df6e689331c0d70)

Please help me review the code.
Thanks

**Comment by dattu1729** [comment]
@nicklam345 , Code reviewed. There are no review comments.

Hi victor,
This defect is fixed. Please do starting.

**Comment by dattu1729** [comment]
@nicklam345 , Code reviewed. There are no review comments.

Hi victor,
This defect is fixed. Please do starting.

**Comment by victordc** [comment]
Dear Dattu,
Testing done & working as expected
Please proceed to do acceptance test

Please see the attached file below

![image](https://cloud.githubusercontent.com/assets/5611431/10117034/65c9ce68-647b-11e5-83d1-935198db214f.png)

**Comment by caesarloh** [comment]
Verified. Working as expected.

**Comment by yj88** [comment]
Approved for release under 1.0.9. CR merged back to trunk.

**Comment by zinse22** [comment]
Released and closed.
